version: '3'
services:
  app-server:
    image: nginx
    container_name: app_server
    expose:
      - 80
    volumes:
      - "./html:/usr/share/nginx/html"
  app-server2:
    image: nginx
    container_name: app_server2
    expose:
      - 80
    volumes:
      - "./html2:/usr/share/nginx/html"
  reverse-proxy:
    image: nginx
    container_name: proxy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf.d:/etc/nginx/conf.d/"
