---
- name: install packages..
  apt:
    name: "{{item.package}}"
    update_cache: yes
  with_items:
    - { package: vim }
    - { package: git }
    - { package: mosh }
    - { package: docker.io }
    - { package: docker-compose }
  tags:
    - setup
